//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public long ContactNo { get; set; }
        public string Address { get; set; }
        public int StatusId { get; set; }
        public string Role { get; set; }
    }
}
